name: ie-bank-frontend

on:
  # Run on any branch except main (development)
  push:
    branches-ignore:
      - main

  # Run on pull requests to main (UAT environment)
  pull_request:
    branches:
      - main

  # Allow manual triggering
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_UAT: czoubi-fe-uat  # Replace with your actual UAT web app name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build -- --mode production --dest dist-uat  ## building the vue.js app using .env.production variables into the dist-uat/ folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app-uat
          path: dist-uat/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app-uat

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}  # Your UAT web app name here
          package: .
